name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Log into the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: hub.majudev.net
        username: ${{ vars.HUB_LOGIN }}
        password: ${{ secrets.HUB_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build the frontend Docker image
      run: |
        cd frontend && docker build -t hub.majudev.net/zwierz/frontend:$IMAGE_TAG .
    - name: Build the backend Docker image
      run: |
        cd backend && docker build -t hub.majudev.net/zwierz/backend:$IMAGE_TAG .
    - name: Build the nginx Docker image
      run: |
        cd nginx && docker build -t hub.majudev.net/zwierz/nginx:$IMAGE_TAG .
    - name: Push the frontend Docker image
      run: |
        docker push hub.majudev.net/zwierz/frontend:$IMAGE_TAG
    - name: Push the backend Docker image
      run: |
        docker push hub.majudev.net/zwierz/backend:$IMAGE_TAG
    - name: Push the nginx Docker image
      run: |
        docker push hub.majudev.net/zwierz/nginx:$IMAGE_TAG
